apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: book-dev
  namespace: openshift-gitops
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    name: ''
    namespace: book-dev
    server: 'https://kubernetes.default.svc'
  source:
    path: config/overlays/dev
    repoURL: 'https://github.com/thomasberrey/person-service-config.git'
    targetRevision: HEAD
  project: default
  syncPolicy:
    automated:
      prune: true
    syncOptions:
      - PruneLast=true
