apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"tekton.dev/v1beta1","kind":"Pipeline","metadata":{"annotations":{},"creationTimestamp":"2022-05-23T17:48:13Z","generation":8,"name":"build-and-push-image","namespace":"book-tekton","resourceVersion":"342107","uid":"1ffabe71-a4e2-46d3-a29d-473754bf8cf1"},"spec":{"params":[{"default":"https://github.com/thomasberrey/person-service.git","name":"git-url","type":"string"},{"default":"main","name":"git-revision","type":"string"},{"default":"quay.io/repository/tberrey/person-service","name":"image-name","type":"string"},{"default":"tberrey","name":"image-username","type":"string"},{"default":"this is a generated hash from quay.io","name":"image-password","type":"string"},{"default":"book-tekton","name":"target-namespace","type":"string"}],"tasks":[{"name":"git-clone","params":[{"name":"url","value":"$(params.git-url)"},{"name":"submodules","value":"true"},{"name":"depth","value":"1"},{"name":"sslVerify","value":"true"},{"name":"deleteExisting","value":"true"},{"name":"verbose","value":"true"},{"name":"gitInitImage","value":"registry.redhat.io/openshift-pipelines/pipelines-git-init-rhel8@sha256:55b0686bbd045c9c77820686318f8a5ff2aff06de566b067f408d27a93bf153c"},{"name":"userHome","value":"/tekton/home"},{"name":"revision","value":"$(params.git-revision)"}],"taskRef":{"kind":"ClusterTask","name":"git-clone"},"workspaces":[{"name":"output","workspace":"shared-workspace"}]},{"name":"package","params":[{"name":"MAVEN_IMAGE","value":"image-registry.openshift-image-registry.svc:5000/openshift/java:latest"},{"name":"GOALS","value":["package"]},{"name":"PROXY_PROTOCOL","value":"http"},{"name":"CONTEXT_DIR","value":"$(params.context-dir)"}],"runAfter":["git-clone"],"taskRef":{"kind":"ClusterTask","name":"maven"},"workspaces":[{"name":"source","workspace":"shared-workspace"},{"name":"maven-settings","workspace":"maven-settings"}]},{"name":"build-and-push-image","params":[{"name":"MAVEN_IMAGE","value":"image-registry.openshift-image-registry.svc:5000/openshift/java:latest"},{"name":"GOALS","value":["package -Dquarkus.container-image.push=true -Dquarkus.container-image.builder=jib -Dquarkus.container-image.image=$(params.image-name) -Dquarkus.container-image.username=$(params.image-username) -Dquarkus.container-image.password=$(params.image-password)"]},{"name":"PROXY_PROTOCOL","value":"http"},{"name":"CONTEXT_DIR","value":"$(params.context-dir)"}],"runAfter":["package"],"taskRef":{"kind":"ClusterTask","name":"maven"},"workspaces":[{"name":"source","workspace":"shared-workspace"},{"name":"maven-settings","workspace":"maven-settings"}]}],"workspaces":[{"name":"shared-workspace"},{"name":"maven-settings"}]}}
  name: build-and-push-image
  namespace: book-tekton
spec:
  params:
  - default: https://github.com/thomasberrey/person-service.git
    name: git-url
    type: string
  - default: the-source
    name: context-dir
    type: string
  - default: main
    name: git-revision
    type: string
  - default: quay.io/repository/tberrey/person-service
    name: image-name
    type: string
  - default: tberrey
    name: image-username
    type: string
  - default: this is a generated hash from quay.io
    name: image-password
    type: string
  - default: book-tekton
    name: target-namespace
    type: string
  tasks:
  - name: git-clone
    params:
    - name: url
      value: $(params.git-url)
    - name: submodules
      value: "true"
    - name: depth
      value: "1"
    - name: sslVerify
      value: "true"
    - name: deleteExisting
      value: "true"
    - name: verbose
      value: "true"
    - name: gitInitImage
      value: registry.redhat.io/openshift-pipelines/pipelines-git-init-rhel8@sha256:55b0686bbd045c9c77820686318f8a5ff2aff06de566b067f408d27a93bf153c
    - name: userHome
      value: /tekton/home
    - name: revision
      value: $(params.git-revision)
    taskRef:
      kind: ClusterTask
      name: git-clone
    workspaces:
    - name: output
      workspace: shared-workspace
  - name: package
    params:
    - name: MAVEN_IMAGE
      value: image-registry.openshift-image-registry.svc:5000/openshift/java:latest
    - name: GOALS
      value:
        - package
        - -DskipTests
    - name: PROXY_PROTOCOL
      value: http
    - name: CONTEXT_DIR
      value: $(params.context-dir)
    runAfter:
    - git-clone
    taskRef:
      kind: ClusterTask
      name: maven
    workspaces:
    - name: source
      workspace: shared-workspace
    - name: maven-settings
      workspace: maven-settings
  - name: build-and-push-image
    params:
    - name: MAVEN_IMAGE
      value: image-registry.openshift-image-registry.svc:5000/openshift/java:latest
    - name: GOALS
      value:
        - package
        - -Dquarkus.container-image.push=true
        - -Dquarkus.container-image.builder=jib
        - -Dquarkus.container-image.image=$(params.image-name)
        - -Dquarkus.container-image.username=$(params.image-username)
        - -Dquarkus.container-image.password=$(params.image-password)
    - name: PROXY_PROTOCOL
      value: http
    - name: CONTEXT_DIR
      value: $(params.context-dir)
    runAfter:
    - package
    taskRef:
      kind: ClusterTask
      name: maven
    workspaces:
    - name: source
      workspace: shared-workspace
    - name: maven-settings
      workspace: maven-settings
  - name: apply-kustomize
    params:
    - name: kustomize-dir
      value: config/manifests
    - name: target-namespace
      value: $(params.target-namespace)
    - name: image-name
      value: '$(params.image-name) '
    runAfter:
    - build-and-push-image
    taskRef:
      kind: Task
      name: kustomize
    workspaces:
    - name: source
      workspace: shared-workspace
  workspaces:
  - name: shared-workspace
  - name: maven-settings
